"""Add users table and user_id foreign keys

Revision ID: 5c987d8e304a
Revises: 0d71ad071a54
Create Date: 2025-12-03 03:34:20.781800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c987d8e304a'
down_revision: Union[str, Sequence[str], None] = '0d71ad071a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from passlib.context import CryptContext
    
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Create users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'GUEST', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Step 2: Insert default admin user
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    admin_password = pwd_context.hash("admin123")  # Change this password after first login!
    
    op.execute(f"""
        INSERT INTO users (username, email, hashed_password, full_name, role, is_active, is_verified)
        VALUES ('admin', 'admin@liara.local', '{admin_password}', 'System Administrator', 'ADMIN', true, true)
    """)
    
    # Step 3: Add user_id columns as nullable first
    op.add_column('calendar_events', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('notes', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Step 4: Assign all existing data to admin user (id=1)
    op.execute("UPDATE calendar_events SET user_id = 1 WHERE user_id IS NULL")
    op.execute("UPDATE notes SET user_id = 1 WHERE user_id IS NULL")
    op.execute("UPDATE tasks SET user_id = 1 WHERE user_id IS NULL")
    
    # Step 5: Make user_id NOT NULL
    op.alter_column('calendar_events', 'user_id', nullable=False)
    op.alter_column('notes', 'user_id', nullable=False)
    op.alter_column('tasks', 'user_id', nullable=False)
    
    # Step 6: Add indexes and foreign keys
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.create_foreign_key(None, 'calendar_events', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_foreign_key(None, 'notes', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_column('tasks', 'user_id')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_column('notes', 'user_id')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_column('calendar_events', 'user_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
