"""add chat session tables

Revision ID: 646650e0d366
Revises: a8f22199b803
Create Date: 2025-12-04 11:17:12.333737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '646650e0d366'
down_revision: Union[str, Sequence[str], None] = 'a8f22199b803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Legacy drop statements removed; objects already deleted by cleanup script.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_memory',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('last_activity', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('context_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('primary_intent', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('redis_key', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('message_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('action_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('session_memory_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('session_memory_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('session_memory_session_id_key')),
    comment='4D Memory - Short-term context storage (syncs with Redis)'
    )
    op.create_index(op.f('idx_session_user'), 'session_memory', ['user_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('idx_session_redis'), 'session_memory', ['redis_key'], unique=False)
    op.create_index(op.f('idx_session_active'), 'session_memory', ['user_id', 'ended_at'], unique=False, postgresql_where='(ended_at IS NULL)')
    op.create_table('web_domain_reputation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('reputation_score', sa.INTEGER(), server_default=sa.text('50'), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('access_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('blocked_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('last_accessed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('has_valid_ssl', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('ssl_checked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('manually_whitelisted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('manually_blacklisted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('admin_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('web_domain_reputation_pkey')),
    sa.UniqueConstraint('domain', name=op.f('web_domain_reputation_domain_key')),
    comment='Cache für Domain-Reputation (Performance + Analytics)'
    )
    op.create_index(op.f('idx_domain_rep_score'), 'web_domain_reputation', ['reputation_score'], unique=False)
    op.create_index(op.f('idx_domain_rep_domain'), 'web_domain_reputation', ['domain'], unique=False)
    op.create_index(op.f('idx_domain_rep_category'), 'web_domain_reputation', ['category'], unique=False)
    op.create_table('web_rate_limit_violations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('violation_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('requests_in_window', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_allowed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('window_minutes', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('web_rate_limit_violations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('web_rate_limit_violations_pkey')),
    comment='Tracking Rate-Limit Überschreitungen (Abuse Detection)'
    )
    op.create_index(op.f('idx_rate_violations_user'), 'web_rate_limit_violations', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_rate_violations_ip'), 'web_rate_limit_violations', ['ip_address', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('content_relations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('strength', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('discovered_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('discovery_method', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('synced_to_neo4j', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('neo4j_relation_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint('strength >= 0::double precision AND strength <= 1::double precision', name=op.f('content_relations_strength_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('content_relations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('content_relations_pkey')),
    sa.UniqueConstraint('user_id', 'source_type', 'source_id', 'target_type', 'target_id', 'relation_type', name=op.f('content_relations_user_id_source_type_source_id_target_type_key')),
    comment='4D Memory - Dimension 4: Relationships between content items (syncs with Neo4j)'
    )
    op.create_index(op.f('idx_relations_type'), 'content_relations', ['relation_type'], unique=False)
    op.create_index(op.f('idx_relations_target'), 'content_relations', ['user_id', 'target_type', 'target_id'], unique=False)
    op.create_index(op.f('idx_relations_strength'), 'content_relations', ['user_id', sa.literal_column('strength DESC')], unique=False)
    op.create_index(op.f('idx_relations_source'), 'content_relations', ['user_id', 'source_type', 'source_id'], unique=False)
    op.create_index(op.f('idx_relations_neo4j_sync'), 'content_relations', ['synced_to_neo4j'], unique=False, postgresql_where='(synced_to_neo4j = false)')
    op.create_table('semantic_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('intent', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('emotion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('importance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding_model', sa.VARCHAR(length=100), server_default=sa.text("'sentence-transformers/all-MiniLM-L6-v2'::character varying"), autoincrement=False, nullable=True),
    sa.Column('embedding_version', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint('importance >= 1 AND importance <= 10', name=op.f('semantic_metadata_importance_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('semantic_metadata_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('semantic_metadata_pkey')),
    sa.UniqueConstraint('user_id', 'content_type', 'content_id', name=op.f('semantic_metadata_user_id_content_type_content_id_key')),
    comment='4D Memory - Dimension 3: Vector embeddings and semantic analysis for similarity search'
    )
    op.create_index(op.f('idx_semantic_user'), 'semantic_metadata', ['user_id'], unique=False)
    op.create_index(op.f('idx_semantic_type'), 'semantic_metadata', ['content_type'], unique=False)
    op.create_index(op.f('idx_semantic_intent'), 'semantic_metadata', ['intent'], unique=False)
    op.create_index(op.f('idx_semantic_importance'), 'semantic_metadata', ['user_id', sa.literal_column('importance DESC')], unique=False)
    op.create_index(op.f('idx_semantic_embedding_hnsw'), 'semantic_metadata', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.create_table('web_blocked_keywords',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('log_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('keyword', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['log_id'], ['web_access_logs.id'], name=op.f('web_blocked_keywords_log_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('web_blocked_keywords_pkey')),
    comment='Tracking blockierter Keywords (Security Analytics)'
    )
    op.create_index(op.f('idx_blocked_keywords_log'), 'web_blocked_keywords', ['log_id'], unique=False)
    op.create_index(op.f('idx_blocked_keywords_keyword'), 'web_blocked_keywords', ['keyword'], unique=False)
    op.create_index(op.f('idx_blocked_keywords_category'), 'web_blocked_keywords', ['category'], unique=False)
    op.create_table('user_location_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('consent_given', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Explicit user consent required for location storage and usage'),
    sa.Column('consent_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_location_preferences_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_location_preferences_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_location_preferences_user_id_key')),
    comment='Privacy-conscious user location storage with explicit consent. IP addresses are NEVER stored.'
    )
    op.create_index(op.f('idx_user_location_user'), 'user_location_preferences', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_location_consent'), 'user_location_preferences', ['user_id', 'consent_given'], unique=False)
    op.create_table('user_privacy_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('allow_location_detection', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('allow_location_storage', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('share_location_with_llm', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('allow_web_search', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('store_search_history', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('allow_search_for_training', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('auto_delete_location_after_days', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True),
    sa.Column('auto_delete_searches_after_days', sa.INTEGER(), server_default=sa.text('7'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_privacy_settings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_privacy_settings_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_privacy_settings_user_id_key')),
    comment='Granular privacy controls for location and web search features'
    )
    op.create_index(op.f('idx_privacy_settings_user'), 'user_privacy_settings', ['user_id'], unique=False)
    op.create_table('user_search_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('search_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('result_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stored_with_consent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('can_be_used_for_training', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('searched_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_search_history_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_search_history_pkey')),
    comment='Optional search history with granular privacy controls. Users can disable or delete.'
    )
    op.create_index(op.f('idx_search_history_user'), 'user_search_history', ['user_id', sa.literal_column('searched_at DESC')], unique=False)
    op.create_index(op.f('idx_search_history_consent'), 'user_search_history', ['user_id', 'stored_with_consent'], unique=False)
    op.create_table('temporal_index',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('sequence_number', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('context_window_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('context_window_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('mood_at_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('energy_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.CheckConstraint('energy_level >= 1 AND energy_level <= 10', name=op.f('temporal_index_energy_level_check')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('temporal_index_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('temporal_index_pkey')),
    sa.UniqueConstraint('user_id', 'content_type', 'content_id', name=op.f('temporal_index_user_id_content_type_content_id_key')),
    comment='4D Memory - Dimension 2: Temporal tracking of all user content with sequence numbers and context windows'
    )
    op.create_index(op.f('idx_temporal_user_timestamp'), 'temporal_index', ['user_id', sa.literal_column('timestamp DESC')], unique=False)
    op.create_index(op.f('idx_temporal_session'), 'temporal_index', ['session_id'], unique=False, postgresql_where='(session_id IS NOT NULL)')
    op.create_index(op.f('idx_temporal_sequence'), 'temporal_index', ['user_id', sa.literal_column('sequence_number DESC')], unique=False)
    op.create_index(op.f('idx_temporal_mood'), 'temporal_index', ['user_id', 'mood_at_time'], unique=False, postgresql_where='(mood_at_time IS NOT NULL)')
    op.create_table('web_access_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('rewritten_query', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('final_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('request_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('intent_risk_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='Layer 1: Query Safety Check'),
    sa.Column('domain_risk_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='Layer 2: Domain Reputation'),
    sa.Column('content_risk_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='Layer 4: Content Filter'),
    sa.Column('response_risk_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True, comment='Layer 5: Response Safety'),
    sa.Column('final_risk_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('risk_level', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('blocked_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('blocked_layer', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('content_length', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_time_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('toxic_content_found', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('pii_removed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('affiliate_links_removed', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('ip_address', postgresql.INET(), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('web_access_logs_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('web_access_logs_pkey')),
    comment='Audit Trail für alle Web-Zugriffe (4-Layer Security)'
    )
    op.create_index(op.f('idx_web_logs_user'), 'web_access_logs', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_web_logs_url'), 'web_access_logs', ['final_url'], unique=False)
    op.create_index(op.f('idx_web_logs_risk'), 'web_access_logs', [sa.literal_column('final_risk_score DESC')], unique=False)
    op.create_index(op.f('idx_web_logs_created'), 'web_access_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_web_logs_blocked'), 'web_access_logs', ['blocked', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###
