"""add_refresh_token_to_users

Revision ID: 7f58a46f0184
Revises: 5c987d8e304a
Create Date: 2025-12-03 04:37:30.012514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f58a46f0184'
down_revision: Union[str, Sequence[str], None] = '5c987d8e304a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('refresh_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_expires')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
